name: Auto-Update Planning
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Chrome
        run: |
          # On utilise sudo pour éviter le "Permission denied"
          sudo npx @puppeteer/browsers install chrome --path /home/runner/work/EDT/EDT/chrome

      - name: Run Scraper
        run: node scrap.js
        env:
          ADE_USER: ${{ secrets.ADE_USER }}
          ADE_PASS: ${{ secrets.ADE_PASS }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          # On indique à Puppeteer où on a installé Chrome
          PUPPETEER_EXECUTABLE_PATH: /home/runner/work/EDT/EDT/chrome/chrome/linux-147.0.7727.57/chrome-linux64/chrome